<?php

class GallerySeeder extends Seeder
{
    public function run()
    {

        $typi_galleries = array(
          array('id' => '1','name' => 'gallery-1','created_at' => '2014-05-09 13:39:31','updated_at' => '2014-05-09 13:39:31'),
          array('id' => '2','name' => 'gallery-2','created_at' => '2014-05-09 15:19:18','updated_at' => '2014-05-09 15:19:18')
        );

$typi_gallery_translations = array(
  array('id' => '1','gallery_id' => '1','locale' => 'fr','status' => '1','title' => 'Paul Cézanne','slug' => 'paul-cezanne','body' => '<h2>Biographie</h2>
<h3>Enfance et origines de la famille Cézanne</h3>
<p>Son père, Louis Auguste Cézanne, est originaire de Saint-Zacharie (Var), propriétaire à Aix-en-Provence (Bouches-du-Rhône)1. La famille de Paul Cézanne possède une chapellerie sur le cours Mirabeau. La famille est relativement aisée et le père fonde une banque, le 1er juin 1848, à laquelle il donne le nom de « Banque Cézanne et Cabassol »2, de son nom propre et de celui de son associé.</p>
<h3>Débuts dans la carrière de peintre</h3>
<p>En 1886, il rompt tout contact avec Émile Zola, qu\'il connaissait depuis son enfance et ses années d\'études au lycée d\'Aix-en-Provence 3. La cause de la brouille est le roman L\'Œuvre (racontant l\'histoire d\'un peintre maudit et pourchassé par le destin incapable d\'achever sa « grande œuvre »), que le peintre a inspiré4. Le 28 avril, il épouse Hortense5. La même année, son père meurt, lui laissant un héritage confortable qui le met à l\'abri financièrement. Sa première exposition personnelle, organisée par le marchand de tableau Ambroise Vollard en 1895 en l\'absence du peintre, se heurte encore à l\'incompréhension du public, mais lui vaut l\'estime des artistes. Sa renommée devient internationale et il remporte à Bruxelles un grand succès lors des expositions des Indépendants. Il se fait construire en 1901-1902 un atelier dans la périphérie d\'Aix : l\'atelier des Lauves.</p>','created_at' => '2014-05-09 13:39:31','updated_at' => '2014-05-09 15:36:22'),
  array('id' => '2','gallery_id' => '1','locale' => 'nl','status' => '1','title' => 'Paul Cézanne','slug' => 'paul-cezanne','body' => '<h2>Levensbeschrijving</h2>
<p>Paul Cézanne werd geboren als zoon van de hoedenhandelaar en latere bankier Louis-Auguste Cézanne en Anne-Elisabeth-Honorine Aubert. Zijn ouders trouwden pas in 1844, na de geboorte van Paul en zijn zus Marie (1841).</p>
<p>Al tijdens zijn schooltijd, vanaf 1856, volgde Cézanne een avondcursus tekenen bij Joseph-Marc Gibert in het museum van Aix. Tussen 1859 en 1861 studeerde Cézanne rechten, maar hij volgde tegelijkertijd teken- en schilderlessen. Hij werkte tijdelijk bij de bank van zijn vader, maar dat beviel hem niet. Tegen de wil van zijn vader koos Cézanne voor de kunst. Hij volgde zijn vriend Émile Zola naar Parijs. Zijn vader, die erg rijk was - hij was na eerst hoedenmaker te zijn geweest stichter van de bank Cézanne &amp; Cabassol - steunde hem vervolgens toch, zodat Cézanne financieel onafhankelijk kon zijn.</p>
<p>Op de Salon d\'Automne van 1907 worden 56 werken van Paul Cézanne tentoongesteld. Emile Bernard publiceerde in Le Mercure de France twee delen met herinneringen aan Cézanne.</p>','created_at' => '2014-05-09 13:39:31','updated_at' => '2014-05-09 15:36:22'),
  array('id' => '3','gallery_id' => '1','locale' => 'en','status' => '1','title' => 'Paul Cézanne','slug' => 'paul-cezanne','body' => '<h2>Life and work</h2>
<p>The Cézannes lived in the town of Cesana now in West Piedmont, and the surname may be of Italian origin.[1] Paul Cézanne was born on 19 January 1839 in Aix-en-Provence, in Provence in the South of France.[2] On 22 February, Paul was baptized in the Église de la Madeleine, with his grandmother and uncle Louis as godparents.[2][3][4][5] His father, Louis-Auguste Cézanne (28 July 1798 – 23 October 1886),[6] was the co-founder of a banking firm that prospered throughout the artist\'s life, affording him financial security that was unavailable to most of his contemporaries and eventually resulting in a large inheritance.[7]</p>
<p>Femme au Chapeau Vert (Woman in a Green Hat. Madame Cézanne.) 1894–1895<br>On the other hand, his mother, Anne Elisabeth Honorine Aubert (24 September 1814 – 25 October 1897),[8] was "vivacious and romantic, but quick to take offence".[9] It was from her that Paul got his conception and vision of life.[9] He also had two younger sisters, Marie and Rose, with whom he went to a primary school every day.[2][10]</p>
<p>At the age of ten Paul entered the Saint Joseph school in Aix.[11] In 1852 Cézanne entered the Collège Bourbon (now Collège Mignet), where he met and became friends with Émile Zola, who was in a less advanced class,[7][10] as well as Baptistin Baille—three friends who would come to be known as "les trois inséparables" (the three inseparables).[12] He stayed there for six years, though in the last two years he was a day scholar.[13] In 1857 he began attending the Free Municipal School of Drawing in Aix, where he studied drawing under Joseph Gibert, a Spanish monk.[14] From 1858 to 1861, complying with his father\'s wishes, Cézanne attended the law school of the University of Aix, while also receiving drawing lessons.[15]</p>
<p>Going against the objections of his banker father, he committed himself to pursuing his artistic development and left Aix for Paris in 1861. He was strongly encouraged to make this decision by Zola, who was already living in the capital at the time. Eventually, his father reconciled with Cézanne and supported his choice of career. Cézanne later received an inheritance of 400,000 francs (£218,363.62) from his father, which rid him of all financial worries.</p>','created_at' => '2014-05-09 13:39:31','updated_at' => '2014-05-09 15:36:22'),
  array('id' => '4','gallery_id' => '2','locale' => 'fr','status' => '1','title' => 'Félix Vallotton','slug' => 'felix-vallotton','body' => '<h2>Biographie</h2>
<p>Felix Vallotton est né à Lausanne d\'une famille bourgeoise protestante1. À l\'âge de 17 ans, il entre à l\'Académie Julian, dont les ateliers sont fréquentés par de nombreux artistes post-impressionnistes ainsi que par les Nabis2. En moins de dix ans, le jeune Suisse parvient à se faire un nom auprès de l\'avant-garde parisienne. Sa renommée devient internationale grâce à ses gravures sur bois et à ses illustrations en noir et blanc qui font sensation. Il participe régulièrement à différents salons (Salon des artistes français, Salon des indépendants, Salon d\'automne).</p>
<p>Vallotton était un travailleur acharné, sans cesse à la recherche de nouvelles formes d\'expression. Touché par l\'horreur de la Première Guerre mondiale, il trouva dans le conflit une source d\'inspiration. Il renoua avec le succès vers la fin de la guerre, avant de mourir en 1925. Il a été inhumé au cimetière de Montparnasse.</p>','created_at' => '2014-05-09 15:19:18','updated_at' => '2014-05-09 15:31:03'),
  array('id' => '5','gallery_id' => '2','locale' => 'nl','status' => '1','title' => 'Félix Vallotton','slug' => 'felix-vallotton','body' => '<h2>Biografie</h2>
<p>Félix Vallotton is in 1865 in geboren. Het talent van Vallotton viel zijn leraren in Lausanne op, zij adviseren zijn ouders om Félix in Parijs te laten studeren. In 1882 schrijft Vallotton zich in voor de Académie Julian. In de eerste tijd legt Vallotton zich met name toe op het portretschilderen. Vanaf 1889 was Hélène Châtenay de levenspartner van Vallotton. Vallotton was een gedreven kunstenaar. Hij schreef kunstkritieken, essays, toneelstukken en zelfs drie romans. Hij heeft een tijdje met beeldhouwen gespeeld, maar het bekendste zijn toch wel zijn drukwerk en schilderijen.</p>
<p>In 1890, na een tentoonstelling van Japans drukwerk gezien te hebben op de École des Beaux Arts, begon Valloton aan een eigen collectie van drukwerk te werken. De simpelheid en de directheid van de Japanse kunst hebben zijn werk beïnvloed. Hij maakte veel gebruik van de druktechnieken, hij speelde met de extreme zwart-wit tegenstellingen van het houtdrukwerk.</p>','created_at' => '2014-05-09 15:19:18','updated_at' => '2014-05-09 15:31:33'),
  array('id' => '6','gallery_id' => '2','locale' => 'en','status' => '1','title' => 'Félix Vallotton','slug' => 'felix-vallotton','body' => '<h2>Life and work</h2>
<p>He was born into a conservative middle-class family in Lausanne, and there he attended Collège Cantonal, graduating with a degree in classical studies in 1882. In that year he moved to Paris to study art under Jules Joseph Lefebvre and Gustave Boulanger at the Académie Julian. He spent many hours in the Louvre, where he greatly admired the works of Holbein, Dürer and Ingres; these artists would remain exemplars for Vallotton throughout his life.[1] Vallotton\'s earliest paintings, chiefly portraits, are firmly rooted in the academic tradition. In 1885 he painted the Ingresque Portrait of Monsieur Ursenbach as well as his first painted self-portrait (seen at left), which received an honorable mention at the Salon des artistes français in 1886.</p>
<p>Self portrait (20 years old), 1885, oil on canvas<br>During the following decade Vallotton painted, wrote art criticism and made a number of prints. In 1891 he executed his first woodcut, a portrait of Paul Verlaine. The many woodcuts he produced during the 1890s were recognized as innovative, and established Vallotton as a leader in the revival of true woodcut as an artistic medium.[2] In the western world, the relief print, in the form of commercial wood engraving, had long been utilized mainly as a means to accurately reproduce drawn or painted images and, latterly, photographs. Vallotton\'s woodcut style was novel in its starkly reductive opposition of large masses of undifferentiated black and areas of unmodulated white. Vallotton emphasized outline and flat patterns, and generally eliminated the gradations and modeling traditionally produced by hatching. He was influenced by post-Impressionism, Symbolism, and especially by the Japanese woodcut: a large exhibition of ukiyo-e prints had been presented at the École des Beaux-Arts in 1890, and Vallotton, like many artists of his era an enthusiast of Japonism, collected these prints.</p>','created_at' => '2014-05-09 15:19:18','updated_at' => '2014-05-09 15:31:33')
);

        DB::table('galleries')->insert( $typi_galleries );
        DB::table('gallery_translations')->insert( $typi_gallery_translations );

    }

}
