<?php

class NewsSeeder extends Seeder {

    public function run()
    {

        $typi_news = array(
            array('id' => '1','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '2','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '3','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '4','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '5','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '6','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '7','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '8','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '9','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '10','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '11','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '12','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '13','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '14','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '15','date' => '2014-03-20 12:33:00','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
        );

        $typi_news_translations = array(
            array('id' => '1','news_id' => '1','locale' => 'fr','status' => '1','title' => 'News','slug' => 'test-de-pge','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '2','news_id' => '1','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-1','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '3','news_id' => '1','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-1','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '4','news_id' => '2','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-1','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '5','news_id' => '2','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-2','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '6','news_id' => '2','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-2','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '7','news_id' => '3','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-2','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '8','news_id' => '3','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-3','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '9','news_id' => '3','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-3','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '10','news_id' => '4','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-3','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '11','news_id' => '4','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-4','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '12','news_id' => '4','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-4','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '13','news_id' => '5','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-4','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '14','news_id' => '5','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-5','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '15','news_id' => '5','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-5','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:37','updated_at' => '2014-03-04 12:33:37'),
            array('id' => '16','news_id' => '6','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-5','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '17','news_id' => '6','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-6','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '18','news_id' => '6','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-6','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '19','news_id' => '7','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-6','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '20','news_id' => '7','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-7','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '21','news_id' => '7','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-7','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '22','news_id' => '8','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-7','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '23','news_id' => '8','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-8','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '24','news_id' => '8','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-8','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '25','news_id' => '9','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-8','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '26','news_id' => '9','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-9','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '27','news_id' => '9','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-9','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '28','news_id' => '10','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-9','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '29','news_id' => '10','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-1','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '30','news_id' => '10','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-1','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '31','news_id' => '11','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-10','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '32','news_id' => '11','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-1','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '33','news_id' => '11','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-1','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '34','news_id' => '12','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-11','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '35','news_id' => '12','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-1','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '36','news_id' => '12','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-1','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '37','news_id' => '13','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-12','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '38','news_id' => '13','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-1','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '39','news_id' => '13','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-1','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '40','news_id' => '14','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-13','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '41','news_id' => '14','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-1','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '42','news_id' => '14','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-1','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '43','news_id' => '15','locale' => 'fr','status' => '1','title' => 'News','slug' => 'news-14','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '44','news_id' => '15','locale' => 'nl','status' => '1','title' => 'News','slug' => 'news-14','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
            array('id' => '45','news_id' => '15','locale' => 'en','status' => '1','title' => 'News','slug' => 'news-14','summary' => '','body' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor. Cras elementum ultrices diam. Maecenas ligula massa, varius a, semper congue, euismod non, mi.','created_at' => '2014-03-04 12:33:38','updated_at' => '2014-03-04 12:33:38'),
        );

        DB::table('news')->insert( $typi_news );
        DB::table('news_translations')->insert( $typi_news_translations );

    }

}